version: '3.8'

services:
  backend-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_NAME=backend-gateway
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always
    depends_on:
      - micro-authen
      - micro-file
      - micro-reports
      - micro-cluster
      - micro-license
      - micro-notification
      - micro-tenant

  micro-authen:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_NAME=micro-authen
    environment:
      - NODE_ENV=production
    restart: always

  micro-file:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_NAME=micro-file
    environment:
      - NODE_ENV=production
    restart: always

  micro-reports:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_NAME=micro-reports
    environment:
      - NODE_ENV=production
    restart: always

  micro-cluster:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_NAME=micro-cluster
    environment:
      - NODE_ENV=production
    restart: always

  micro-license:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_NAME=micro-license
    environment:
      - NODE_ENV=production
    restart: always

  micro-notification:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_NAME=micro-notification
    environment:
      - NODE_ENV=production
    restart: always

  micro-tenant:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_NAME=micro-tenant
    environment:
      - NODE_ENV=production
    restart: always

  # Database
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #     - POSTGRES_DB=${POSTGRES_DB}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: always

  # Redis for caching
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    restart: always

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend-gateway
    restart: always

volumes:
  # postgres_data:
  redis_data: 